### ISSUE TITLE
locks' bazaar of ideas

### ISSUE THREAD

**Issue by locks** [AlexRodwell/netrunner-east-anglia-stream-overlay#10]
- [x] #15
- [x] #16
- [x] A way to set Corp and Runner IDs at beginning of match and switch
- [x] "Reset game state" button
- [x] Toggle to hide "win points"
- [x] #13
- [x] Save current state to localStorage so it survives refreshes
- [x] Thread tracker
- [x] Separate settings (what to show), player info (name/pronouns/ids), and game state (agendas, card displsay) sections
- [x] Switch player sides (in case they sat the "wrong" way around in the cameras)
- [ ] #14

**Comment by AlexRodwell** [comment]
The following have already been added in my WIP branch https://github.com/AlexRodwell/netrunner-stream-overlay/tree/refactor-wip:
- Fuzzy search
- Set players corp/runner decks (this is on main branch currently)
- Reset game state
- Toggle to hide win points
- Save current state to localStorage
- Threat tracker
- Separate settings (I moved the 'global' settings to a modal, as well as all other non-player side settings)
- Flip/switch player sides

**Comment by locks** [comment]
You're an MVP 😍

**Comment by AlexRodwell** [comment]
Closing, as the last checklist item is a separate issue, so this issue is effectively complete.
